import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import MaxWidthWrapper from "@/components/max-width-wrapper";

const inter = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Navarrete Science",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MaxWidthWrapper>
        <body className={inter.className}>{children}</body>
      </MaxWidthWrapper>
    </html>
  );
}
